### ISSUE TITLE
Can I just use your blog generator?

### ISSUE THREAD

**Issue by meritozh** [xinhuang/xinhuang.github.com#1]
Hi, I like the style of your blog, so can I just use your generator?

By the way, `walk()` method has been extracted from `fs-extra` as a new module name `klaw`. I think you should update dependencies.

**Comment by meritozh** [comment]
And if you allow me to use, please add a usage. Thanks.

**Comment by xinhuang** [comment]
Sorry for late response. Just take it. I will add a usage later.

**Comment by meritozh** [comment]
thx
